server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native # native file repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eGovFramework/egovframe-msa-template-config
          username: egovframesupport
          password:
          search-paths: config
          default-label: main
#        native:
#          search-locations: file://${user.home}/workspace
# rabbitmq server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# rabbitmq 다른 서비스에 전파하도록
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh