server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native # native file repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eGovFramework/egovframe-msa-template-config
          username: egovframesupport
          password:
          search-paths: config
          default-label: main
#        native:
#          search-locations: file://${user.home}/workspace